### ISSUE TITLE
Retrieve data from backend services through action queue

### ISSUE THREAD

**Issue by janjaapbos** [aaivazis/nautilus#27]
Can AMQP also be used a the broker (api) service for routing requests, instead of http proxy requests?

**Comment by aaivazis** [comment]
I'm not sure I understand the question. In order for the API gateway to cause an effect on a service, they have to dispatch an action using [nautilus.network.dispatchAction](http://aaivazis.github.io/nautilus/_modules/nautilus/network/dispatch.html#dispatchAction). Currently this takes a dictionary with two keys, `type` and `payload` but I think we should probably split that into two different arguments to the function. 

This sends the event to all services - it's up to the individual service if it wants to react or not. The API gateway has no idea who is going to do what when it fires the action. This lets me easily drop in logging or caching services that can also respond to a particular action.

The model services assume nautilus conventions for the action types in order to respond, in order to reuse these conventions you can call the helper functions [here](http://aaivazis.github.io/nautilus/internals/nautilus.conventions.html). I would love to have some sort of abstraction over common mutations so the user doesn't have to remember to use the conventions.

**Comment by janjaapbos** [comment]
Ok, I think my question is not valid then. Perhaps I am not testing it
correctly, as the logging show http request at the services, but may be
that is just the AMQP payload.

In my testing, using recipes / api, i have 4 services running: api,
recipes, ingredients, recipeIngredients. They all run on the same hosts,
with different ports. From my desktop I query with my browser the api
service. I then see e.g. the recipe service logging that appears to be
coming from http.

One thing that perhaps set me on the wrong foot, is that the services
register themselves with consul using their web address and port. So I
thought these were use by the api to reach them.

    consulSession.agent.service.register(
        name = service.name,
        service_id = service.consul_name,
        port = service.app.config['PORT'],
    )

I am new at consul, so probably need to read up on that, how it is used.

2016-02-25 22:21 GMT+01:00 Alec Aivazis <notifications@github.com>:

**Comment by aaivazis** [comment]
Ah, I understand the source of your confusion. 

The api gateway uses the location of the service to *retrieve* data, but it does not target a specific service when dispatching actions.

**Comment by janjaapbos** [comment]
Why is retrieving data not handled as dispatching actions through AMQP, and the data is return through AMQP message as well?

**Comment by aaivazis** [comment]
Huh, that's an interesting idea. I'm definitely open to exploring it and absolutely love the idea of removing consul from this interaction. My immediate response is that there might be many actions waiting to be handled which would potentially cause a long delay between asking for the message and getting the data. Also, it sort of serializes the request handling but if we can get the same performance, it's a much cleaner picture from an architectural standpoint.

**Comment by janjaapbos** [comment]
Great. I'll make a use case description for it, so we can discuss further.

2016-02-26 8:52 GMT+01:00 Alec Aivazis <notifications@github.com>:

**Comment by janjaapbos** [comment]
The api frontend should handle many concurrent requests that access the api from HTTP. The complete request (body and HTTP headers) are forwarded to AMQP, using the url/path address a a routing key. The HTTP headers can be used as AMQP message properties.

The processing chain of HTTP/AMQP should be non-blocking on both the api frontend and services. The incoming HTTP requests, relayed AMQP requests, and the AMQP / HTTP responses must be correlated using an identifier. The frontend can keep a queue of HTTP request using the correlation_id to match AMQP responses.

A month ago I did a short experiment like this, using eventlet (https://github.com/eventlet/eventlet) and amqpy (https://github.com/veegee/amqpy). The chain of requests / responses where handled as events. The green threads where used by import_patched of amqpy.

Perhaps this can be done with flask / pika in another way, not using green threads but some other mechanism.

Besides forwarding to AMQP / services, the api frontend can also do some initial screening of the incoming requests, e.g. checking authorisation headers or just preventing denial of service. 

All components should scale horizontally, multiple frontends, multiple AMQP servers (cluster), and multiple services for the same entity / domain.

**Comment by aaivazis** [comment]
Awesome - this looks mostly good to me. A few points:

* The api gateway powers a single graphql endpoint so we can't use the url to determine what data we need. The [ServiceObjectType](http://aaivazis.github.io/nautilus/internals/nautilus.api.objectTypes.html#module-nautilus.api.objectTypes.serviceObjectType) and [Connection](http://aaivazis.github.io/nautilus/internals/nautilus.api.fields.html#module-nautilus.api.fields.connection) combo (as seen in the [example](https://github.com/aaivazis/nautilus/blob/master/example/services/api.py)) provide a nice way to map graphql objects to backend requests so maybe we can fire the action and wait for the appropriate response as part of resolving a connection.
* I'd be curious to see a performance comparison of eventlet and pika. There seems to be tons of praise online about the performance of eventlet so initially i'm all for using it. I think the change would only affect the [consumer](http://aaivazis.github.io/nautilus/internals/nautilus.network.consumers.html) so it should be pretty easy to swap both packages and see which performs better.
* The api gateway already handles authorization for a specific pieces of data (see [here](http://aaivazis.github.io/nautilus/intro/auth.html)) but there is currently no defense against DoS, definitely something we should add.

**Comment by aaivazis** [comment]
By the way, I'm not sure if you've seen it (you probably have) but I wanted to record the existence of [this](http://stackoverflow.com/questions/7974618/can-eventlet-manage-an-amqp-connection-with-messages-passing-asynchronously-both) excellent post about rabbit mq + eventlet on stackoverflow.

**Comment by janjaapbos** [comment]
Thanks for the link! I did not know about it.

Shall I try to quickly throw together an eventlet + amqpy relay implementation for the service? We can work on that in a separate branch first if you like. I already got the web service running on eventlet wsgi with a few lines changed in nautilus/services/service.py.

I would like for the services (and the api gateway) to be both addressable through HTTP and AMQP. In some cases it is easier to directly connect to a service through HTTP (e.g. local admin, testing etc.).

**Comment by aaivazis** [comment]
Yea, that sounds great! 

re: addressing services - I agree. In general, we shouldn't address specific services in amqp, but like you say it's very nice to go to `localhost:8000/admin` and mess around with the underlying data model. 

The ApiGateway might be an exception for performance reasons but I want to keep the action queue global. I'm more inclined to say that the data retrieval should just happen through a separate exchange since it's a different part of the uni-directional flow. 

I think routes are good as general descriptions (ie, to designate an error, mutation, etc.) but I want to stay away from more specific routes, that sort of configuration belongs in the action data (either type or payload). One option is to make the shift where the `type` designates the route... that would save us cpu cycles wasted deserializing events we don't care about. But that's an implementation detail we can discuss later. Immediately, i'm concerned how one would designate which types/routes the handler responds to. I quite like the handler just being a single function. Maybe we can make `payload` argument lazy and pass the route to the function?

**Comment by aaivazis** [comment]
Sorry i kind of got side tracked there, but i'm very excited to explore moving more of the infrastructure to amqp, seems like the right move. Feel free to make a new branch so we can start to see what this would look like.

**Comment by janjaapbos** [comment]
The advantage of using specific routes is that we can leverage the AMQP
exchange mechanisms for distributing events / actions.

For instance, recipe.id1.delete, or some meta info in the route would be
helpful for distribution management without looking at the message.

Further, we can use amqp message properties to set more detailed meta info
(e.g. content type), so the message it self can also be a binary blob in
some cases.

I would like to use this mechanism not only for graphql requests, but for
any type of HTTP requests.


2016-02-26 22:00 GMT+01:00 Alec Aivazis <notifications@github.com>:

**Comment by aaivazis** [comment]
I agree with you the more I think about it. However, my gut still says to separate the two halves of the loop it into different exchanges. 

Also, I'm not sure what other sorts of http requests would happen besides graphql ones? In this picture, the graphql api only exists at the gateway and all inter-service communication is brokered through amqp. It seems to me that the only place non-graphql http requests get handled is in very specialized situations like the auth service or other clients. In those situations, there is no need for mutating the other services. In fact, that's what makes it "unique" so it would seem like we don't need to have event-based handling for normal http requests. Maybe I'm missing something though

**Comment by janjaapbos** [comment]
Yes, we can use separate AMQP exchanges. In any case have different
consumer channels.

I'm not sure what types of content is supported by graphql responses. Is
binary data possible as well?

How about uploading & downloading files? Or perhaps even socket IO
requests? It would be nice to have a common endpoint gateway that can scale
and distribute these kind of requests (from e.g. a react javascript
application) to arbitrary services.


2016-02-26 22:33 GMT+01:00 Alec Aivazis <notifications@github.com>:

**Comment by aaivazis** [comment]
I'm fairly certain the request object is passed to the resolve handler of a graphql field that includes attached data. In my personal projects, I've been sending base64 encoded versions of files which lets me treat everything as a string :wink: 

Currently, there is not much awareness of the javascript side of things, but I want to completely support the react/relay ecosystem and hook into their subscription model. You already can specify your subscriptions through the graphql api (see [here](http://graphql.org/blog/subscriptions-in-graphql-and-relay/)) and there's already graphene support. I have some thoughts on ways to tie the requested subscription to amqp routes, which lets us "whitelist" backend events and pass them onto the subscriptions that need them. If we do things correctly (ie, conforming to the "relay way"), this should give us realtime for free in react clients. Extending this to a general socket.io connection should be really easy - and probably the job for a standalone service, not the api gateway.

**Comment by aaivazis** [comment]
If you don't mind, I'd like to close this issue and open up an issue for each of the topics here (retrieving data through amqp, event routing, subscriptions) so we can stay a bit more organized.

**Comment by janjaapbos** [comment]
Great! My knowledge of this is limited, I really like to get started on
react/relay.

Yes, go ahead and close this issue.

2016-02-26 22:56 GMT+01:00 Alec Aivazis <notifications@github.com>:
